name: Docker develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, test]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --tag ${{ github.event.repository.name }}:${GITHUB_REF##*/} --file src/Presentation/Dockerfile